version: '3'
services:
   node:
     build:
       context: .
       dockerfile: Dockerfile_node
     volumes:
      - ./:/usr/src/app-movie
     command: sh -c "cd hooked && yarn start"
     ports:
      - "3001:3001"